### PR TITLE
Update RPM packaging

### PR DESCRIPTION
**Pull request by opoplawski**
This tries to do a few things:
* Set better permissions on config files
* Fix an apparent typo for /etc/sysconfig/evebox
* Mark config files as config files so they are not replaced on upgrade
* Actually own the real config file
This is untested as I don't have the ability to build evebox and evebox RPMs with fpm at the moment.

### CODE REVIEW

**Comment by jasonish** [comment]
This installs config files, rather than just their examples.  I'm not sure if I want to do that.  By installing "examples", we can overwrite them on upgrade so a valid example is always available.  Plus many installation scenarios don't require a configuration file, so I'm not sure this is actually an improvement here.

**Comment by opoplawski** [comment]
How about this then?  I think it's pretty important to install the config files with proper permissions.

**Comment by jasonish** [comment]
I can add a default config file with the correct permissions, but the file has to be blank I think.  The examples are not good as a default.

**Comment by opoplawski** [comment]
I guess I would suggest a completely commented out version.

**Comment by jasonish** [comment]
Closing.  The RPM and Debian packages will no include a minimal configuration file that suits 90% of most peoples needs.

**Pull request closed without merging**
